### PR TITLE
AWB initial code review / clean-up

### PR DESCRIPTION
**Pull request by abrinke1**
I went through the NTuple package, in particular the updates for 2017, and cleaned up and fixed a few things.  Probably the biggest change was making the 2016 vs. 2017 settings configurable, and applying that to the Jet ID, muon efficiencies, and Rochester corrections.   I figured it would be easiest if we stay compatible between 2016 and 2017 starting now, rather than trying to re-synchronize in several months.

A few other small changes as well:
  * Updated electron cut-based ID
  * Updated list of always-unprescaled single muon triggers in 2017
  * Updated event filters for MET

Cheers,
Andrew

### CODE REVIEW

**Comment by abrinke1** [comment]
@bortigno I don't know if you want to take a look at this first, or if I should just go ahead and merge.  I'm going to start working more on the Analyzer code now :)

**Comment by bortigno** [comment]
I was thinking of keeping the possibility of running on 2016 based on tags and branches rather than a series of "if"  and flags in the code. I am worried that it could make the code more confusing and bug-prone. I doubt we will ever reprocess 2016 again. 2018 and 2017 instead might need to run at the same time.

A couple of questions on your PR:

1. I see you reverted the SF back to ROOT. Is there a problem with the JSON file?

2. I am also not sure to understand your edits on the MET filters: I updated them already for 2017 data and MC use, and it seems that you added some old filters (for example Flag_badMuons) which are not recommended for 2017 data anymore?

**Comment by abrinke1** [comment]
Hi Pier,
I think it would be best to keep open the possibility of re-processing the 2016 dataset.  There's a good chance we will have improvements (e.g. muon mometum corrections) that would improve the sensitivity of the 2016 dataset.  Also, in our previous analysis we did not use the "legacy" ReReco, which should have better performance / smaller uncertainties for the VBF channels.  Also, a good way to get around statistical limitations is to combine similar regions across all 3 years, rather than having separate 2016, 2017, and 2018 categories.  I'm not saying this is *going* to happen, but if we make the new code incompatible with 2016, then it will make it much, much harder to re-process the 2016 data while outputting NTuples in a format consistent with the 2017/2018 data.  Given that it doesn't take too much work to add 2016/2017 switches in the NTuplizer, I'd rather do that than cross the point of no return.

Regarding your questions:
1. Did I revert the SF back to ROOT for 2017 as well?  If so, that wasn't intentional.
2. I don't know whether Flag_badMuons is still relevant for the 2016 data, so I decided to keep it in for now.

Probably simplest to discuss these details in person, maybe tomorrow.

Cheers,
Andrew

**Comment by bortigno** [comment]
Hey Andrew, 
Thanks for answering. I definitely agree we should keep the code compatible with 2016. When confronted with this problem, I opted for a release-based design (you can look at some gitflow example to see what I have in mind) thinking it is a good fit for our needs and easier to maintain. We would have a release for each dataset. That does not mean that we can not backport developments, but it would avoid duplication of code, generally an unwise code practise. We can discuss this week but I would rather roll back on that.

**Pull request merged**
